name: Manual2
on:
  workflow_dispatch:
    inputs:
      log-level:
        type: choice
        options:
          - info
          - warn
          - error
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - echo "{{inputs.log-level}}"
